//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PlayerFramework.CaptionSettings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PlayerFramework.CaptionSettings.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption Settings.
        /// </summary>
        internal static string CaptionSettings {
            get {
                return ResourceManager.GetString("CaptionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual.
        /// </summary>
        internal static string Casual {
            get {
                return ResourceManager.GetString("Casual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursive.
        /// </summary>
        internal static string Cursive {
            get {
                return ResourceManager.GetString("Cursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depressed edge.
        /// </summary>
        internal static string DepressedEdge {
            get {
                return ResourceManager.GetString("DepressedEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Shadow.
        /// </summary>
        internal static string DropShadow {
            get {
                return ResourceManager.GetString("DropShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        internal static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        internal static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size (%).
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Style.
        /// </summary>
        internal static string FontStyle {
            get {
                return ResourceManager.GetString("FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monospace Sans Serif.
        /// </summary>
        internal static string MonospaceSansSerif {
            get {
                return ResourceManager.GetString("MonospaceSansSerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monospace Serif.
        /// </summary>
        internal static string MonospaceSerif {
            get {
                return ResourceManager.GetString("MonospaceSerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        internal static string Outline {
            get {
                return ResourceManager.GetString("Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaa Bbb Ccc Ddd.
        /// </summary>
        internal static string PreviewText {
            get {
                return ResourceManager.GetString("PreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proportional Sans Serif.
        /// </summary>
        internal static string ProportionalSansSerif {
            get {
                return ResourceManager.GetString("ProportionalSansSerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proportional Serif.
        /// </summary>
        internal static string ProportionalSerif {
            get {
                return ResourceManager.GetString("ProportionalSerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raised edge.
        /// </summary>
        internal static string RaisedEdge {
            get {
                return ResourceManager.GetString("RaisedEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semitransparent.
        /// </summary>
        internal static string Semitransparent {
            get {
                return ResourceManager.GetString("Semitransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smallcaps.
        /// </summary>
        internal static string Smallcaps {
            get {
                return ResourceManager.GetString("Smallcaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid.
        /// </summary>
        internal static string Solid {
            get {
                return ResourceManager.GetString("Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Color.
        /// </summary>
        internal static string WindowColor {
            get {
                return ResourceManager.GetString("WindowColor", resourceCulture);
            }
        }
    }
}
