//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PlayerFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PlayerFramework.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more info....
        /// </summary>
        public static string AdLinkLabel {
            get {
                return ResourceManager.GetString("AdLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio tracks.
        /// </summary>
        public static string AudioSelectionButtonLabel {
            get {
                return ResourceManager.GetString("AudioSelectionButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed captions.
        /// </summary>
        public static string CaptionSelectionButtonLabel {
            get {
                return ResourceManager.GetString("CaptionSelectionButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string DefaultAudioStreamName {
            get {
                return ResourceManager.GetString("DefaultAudioStreamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string DeselectedIdentifierText {
            get {
                return ResourceManager.GetString("DeselectedIdentifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration/Skip ahead.
        /// </summary>
        public static string DurationButtonLabel {
            get {
                return ResourceManager.GetString("DurationButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video failed to play..
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit full-screen.
        /// </summary>
        public static string ExitFullScreenButtonLabel {
            get {
                return ResourceManager.GetString("ExitFullScreenButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast forward.
        /// </summary>
        public static string FastForwardButtonLabel {
            get {
                return ResourceManager.GetString("FastForwardButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-screen.
        /// </summary>
        public static string FullScreenButtonLabel {
            get {
                return ResourceManager.GetString("FullScreenButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go live.
        /// </summary>
        public static string GoLiveButtonLabel {
            get {
                return ResourceManager.GetString("GoLiveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High definition.
        /// </summary>
        public static string HighDefinitionLabel {
            get {
                return ResourceManager.GetString("HighDefinitionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD.
        /// </summary>
        public static string HighDefinitionText {
            get {
                return ResourceManager.GetString("HighDefinitionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string LoadButtonLabel {
            get {
                return ResourceManager.GetString("LoadButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string MuteButtonLabel {
            get {
                return ResourceManager.GetString("MuteButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PauseButtonLabel {
            get {
                return ResourceManager.GetString("PauseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayButtonLabel {
            get {
                return ResourceManager.GetString("PlayButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant replay.
        /// </summary>
        public static string ReplayButtonLabel {
            get {
                return ResourceManager.GetString("ReplayButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string RetryButtonLabel {
            get {
                return ResourceManager.GetString("RetryButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string RetryInstructionsText {
            get {
                return ResourceManager.GetString("RetryInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind.
        /// </summary>
        public static string RewindButtonLabel {
            get {
                return ResourceManager.GetString("RewindButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (On).
        /// </summary>
        public static string SelectedIdentifierText {
            get {
                return ResourceManager.GetString("SelectedIdentifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal strength.
        /// </summary>
        public static string SignalStrengthLabel {
            get {
                return ResourceManager.GetString("SignalStrengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip ahead.
        /// </summary>
        public static string SkipAheadButtonLabel {
            get {
                return ResourceManager.GetString("SkipAheadButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \+ss\s.
        /// </summary>
        public static string SkipAheadPointerOverStringFormat {
            get {
                return ResourceManager.GetString("SkipAheadPointerOverStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip back.
        /// </summary>
        public static string SkipBackButtonLabel {
            get {
                return ResourceManager.GetString("SkipBackButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \-ss\s.
        /// </summary>
        public static string SkipBackPointerOverStringFormat {
            get {
                return ResourceManager.GetString("SkipBackPointerOverStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string SkipNextButtonLabel {
            get {
                return ResourceManager.GetString("SkipNextButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string SkipPreviousButtonLabel {
            get {
                return ResourceManager.GetString("SkipPreviousButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow motion.
        /// </summary>
        public static string SlowMotionButtonLabel {
            get {
                return ResourceManager.GetString("SlowMotionButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard definition.
        /// </summary>
        public static string StandardDefinitionLabel {
            get {
                return ResourceManager.GetString("StandardDefinitionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD.
        /// </summary>
        public static string StandardDefinitionText {
            get {
                return ResourceManager.GetString("StandardDefinitionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopButtonLabel {
            get {
                return ResourceManager.GetString("StopButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time elapsed/Skip back.
        /// </summary>
        public static string TimeElapsedButtonLabel {
            get {
                return ResourceManager.GetString("TimeElapsedButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek.
        /// </summary>
        public static string TimelineLabel {
            get {
                return ResourceManager.GetString("TimelineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining/Skip ahead.
        /// </summary>
        public static string TimeRemainingButtonLabel {
            get {
                return ResourceManager.GetString("TimeRemainingButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h\:mm\:ss.
        /// </summary>
        public static string TimeSpanReadableFormat {
            get {
                return ResourceManager.GetString("TimeSpanReadableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        public static string UnmuteButtonLabel {
            get {
                return ResourceManager.GetString("UnmuteButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string VolumeLabel {
            get {
                return ResourceManager.GetString("VolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume/Mute.
        /// </summary>
        public static string VolumeMuteButtonLabel {
            get {
                return ResourceManager.GetString("VolumeMuteButtonLabel", resourceCulture);
            }
        }
    }
}
